Disassemble RTC setup dialog and slot machine minigame (bank $24)
pret/pokegold-spaceworld pull request #87
Opened 2021-01-21 06:21 UTC by ZoomTen

Also initial cry header pointer and SFX pointer ripping, since I forgot I have those in `master` as well

2021-01-25 14:12 UTC, Rangi42 commented on audio/cries.asm
> +	dbw $3C, $57C5
Can you add shims for each cry header so these can use `dba Cry_Nidoran_M`, etc?

2021-01-25 14:13 UTC, Rangi42 commented on audio/sfx.asm
> +	dbw $3C, $43BE
Likewise add shims for these, even just `Sfx_01`, `Sfx_02`, etc.

2021-01-25 14:16 UTC, Rangi42 commented on engine/menu/set_clock_dialog.asm
> +UP_ARROW	equ $f0
Capitalize `EQU`.

2021-01-25 14:17 UTC, Rangi42 commented on engine/menu/set_clock_dialog.asm
> +;Print up arrow
Space after semicolon: `; Print up arrow`.

2021-01-25 14:19 UTC, Rangi42 commented on macros/wram.asm
> +\1StopDelay::      db
Spacing

2021-01-25 14:20 UTC, Rangi42 commented on ram/wram.asm
> +
Remove trailing space.

2021-01-25 14:23 UTC, Rangi42 requested changes
Please see the comments for requested changes.

Also, the new PNGs look unusually large. Check whether they're encoded as 2-bit grayscale. Programs like pngcrush or optipng may fix them; the output of pokecrystal's gfx.py tool is also correctly encoded. (I usually convert a PNG to 2BPP with gfx.py and then back to make sure it's right.)

2021-01-25 18:08 UTC, Rangi42 commented on audio/sfx.asm
> +	dba Sfx_6c
Add newlines at the end of files.

2021-01-25 18:12 UTC, Rangi42 requested changes
Please fix that missing newline and the two conflicting files.

2021-01-26 03:09 UTC, ZoomTen commented
Just woke up, everything should be fixed hopefully

2021-01-26 03:29 UTC, merged